spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: ${seckill.datasource.driver-class-name}
    url:  jdbc:mysql://${seckill.datasource.host}:${seckill.datasource.port}/${seckill.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${seckill.datasource.username}
    password: ${seckill.datasource.password}
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.leechee.pojo

logging:
  level:
    com.leechee.mapper: debug